try new init script

diff --git a/files/ipfs b/files/ipfs
--- a/files/ipfs
+++ b/files/ipfs
@@ -1,102 +1,67 @@
 #!/bin/sh
 ### BEGIN INIT INFO
-# Provides:          ipfs daemon
-# Required-Start:    $local_fs $remote_fs $network $syslog $named
-# Required-Stop:     $local_fs $remote_fs $network $syslog $named
+# Provides:          ipfs
+# Required-Start:    $local_fs $network $named $time $syslog
+# Required-Stop:     $local_fs $network $named $time $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Starts the ipfs daemon
-# Description:       Starts the ipfs daemon using the start-stop-daemon
+# Description:       ipfs daemon
 ### END INIT INFO
 
-# Author: Dylan Powers <dylan.kyle.powers@gmail.com
+SCRIPT=/usr/local/bin/ipfs
+RUNAS=ipfs
 
-PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
-DESC="ipfs daemon"
-NAME=ipfs
-DAEMON=/usr/local/bin/ipfs
-DAEMON_ARGS="daemon --mount"
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
+PIDFILE=/var/run/ipfs.pid
+LOGFILE=/var/log/ipfs.log
 
-IPFS_PATH=/var/lib/ipfs
-IPFS_USER=ipfs
-
-# Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
-
-# Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
-
-# Load the VERBOSE setting and other rcS variables
-. /lib/init/vars.sh
-
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
-# and status_of_proc is working.
-. /lib/lsb/init-functions
-
-#
-# Function that starts the daemon/service
-#
-do_start() {
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test >/dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile \
-	                  --background --chuid $IPFS_USER --no-close \
-	                  --exec /usr/bin/env IPFS_PATH="$IPFS_PATH" $DAEMON 2>>/var/log/ipfs.log 1>/dev/null \
-	                  -- $DAEMON_ARGS \
-    || return 2
+start() {
+  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
+    echo 'Service already running' >&2
+    return 1
+  fi
+  echo 'Starting service…' >&2
+  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
+  su -c "$CMD" $RUNAS > "$PIDFILE"
+  echo 'Service started' >&2
 }
 
-#
-# Function that stops the daemon/service
-#
-do_stop() {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
+stop() {
+  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
+    echo 'Service not running' >&2
+    return 1
+  fi
+  echo 'Stopping service…' >&2
+  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
+  echo 'Service stopped' >&2
+}
 
-	# Delete the pid
-	rm -f $PIDFILE
-	return "$RETVAL"
+uninstall() {
+  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
+  local SURE
+  read SURE
+  if [ "$SURE" = "yes" ]; then
+    stop
+    rm -f "$PIDFILE"
+    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
+    update-rc.d -f ipfs remove
+    rm -fv "$0"
+  fi
 }
 
 case "$1" in
   start)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-		do_start
-		case "$?" in
-			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-		esac
-		;;
+    start
+    ;;
   stop)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-		do_stop
-		case "$?" in
-			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-		esac
-		;;
-  status)
-		status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-		;;
-	restart)
-		do_stop
-		do_start
-		;;
+    stop
+    ;;
+  uninstall)
+    uninstall
+    ;;
+  restart)
+    stop
+    start
+    ;;
   *)
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
-	exit 3
-	;;
+    echo "Usage: $0 {start|stop|restart|uninstall}"
 esac
